### ISSUE TITLE
implementation project not resolved

### ISSUE THREAD

**Issue by 337240552** [vanniktech/gradle-dependency-graph-generator-plugin#104]
if i have a dependency
`
    implementation project(":moment_api")
`

this module cannot resolved

**Comment by vanniktech** [comment]
Can you try the 0.6.0-SNAPSHOT?

**Comment by balazsbanyai** [comment]
+1

**Comment by vanniktech** [comment]
Is this still an issue?

**Comment by balazsbanyai** [comment]
Yes, it's an issue.

**Comment by balazsbanyai** [comment]
There is a different issue with 0.6.0-snapshot: The direct dependencies are included from both configurations, but the transitive ones are not. I also tried the _projectGenerator_, it's a nice touch that it distinguishes the api/impl dependencies with solid/dotted arrow.

**Comment by vanniktech** [comment]
Seems like we've got everything covered now. If not, feel free to create a new issue.
