### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by s101d1** [vanniktech/gradle-dependency-graph-generator-plugin#106]
I'm not really clear about the usage of the plugin.

I have added the plugin into `build.gradle`:

```
plugins {
  id "com.vanniktech.dependency.graph.generator" version "0.5.0"
}
```
Then I run it with command like:

`$ ./gradlew generateDependencyGraph`

It run successfully without error, but I don't see any result image file in the project directory.

The [documentation](https://github.com/vanniktech/gradle-dependency-graph-generator-plugin#usage) doesn't mention clearly what file it produced after running the command?

Could you explain how the image file produced?

**Comment by s101d1** [comment]
Never mind, I found out the result files are located in `build/reports/dependency-graph` directory, maybe you should add this information in the documentation.

**Comment by rumax** [comment]
> Never mind ...

It also could be added to readme, or even make it configurable. So that is is possible to specify the output folder

**Comment by mamatagelanee07** [comment]
Agree! Needed to find this issue to see where it's been created!
