### ISSUE TITLE
0.6.0 release schedule

### ISSUE THREAD

**Issue by bjorndarri** [vanniktech/gradle-dependency-graph-generator-plugin#107]
I've been using the 0.6.0-SNAPSHOT version without problems for a while now (after #86 was resolved), but it would be so much more convenient if it was available in a public repository.

Any chance of a 0.6.0 release in the near future?

**Comment by ataraxus** [comment]
Would also love to see a new release! thanks!

**Comment by tokuhirom** [comment]
@vanniktech could you release this?

**Comment by vanniktech** [comment]
Once we have some solutions for https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/104 & https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/108
