### ISSUE TITLE
Save plugin output to build/reports/dependency-graph instead of build

### ISSUE THREAD

**Issue by Thunderforge** [vanniktech/gradle-dependency-graph-generator-plugin#11]
Right now, the plugin outputs to the base level of the `build` directory. It would be more idiomatic to place it in `build/reports/dependency-graph` (or a similarly named directory. This matches the behavior of the default Gradle plugins (e.g. Jacoco, Ktlint, tests).

It may be worth looking into the [Reporting](https://docs.gradle.org/current/dsl/org.gradle.api.reporting.Reporting.html) API, which those tasks use. If not, then it would still be good to put it there.

**Comment by vanniktech** [comment]
Sure, we can move it. I don't think CSV and HTML reports are necessary though and hence we could just move it there.

**Comment by Thunderforge** [comment]
Fair enough. This would also be advantageous if the plugin allowed additional output formats (I'm currently writing a request for that).
