### ISSUE TITLE
class 'java.util.ArrayList' to class 'org.gradle.api.NamedDomainObjectContainer' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: 

### ISSUE THREAD

**Issue by baiguanchao** [vanniktech/gradle-dependency-graph-generator-plugin#114]
Cannot cast object '[Generator(name=firebaseLibraries, include=build_kiklblr7frei26qxkxd61prc$_run_closure1@35c8bfb3, children=build_kiklblr7frei26qxkxd61prc$_run_closure2@135786bf, dependencyNode=build_kiklblr7frei26qxkxd61prc$_run_closure3@167d2826, projectNode=(guru.nidi.graphviz.model.MutableNode, org.gradle.api.Project) -> guru.nidi.graphviz.model.MutableNode, label=null, includeConfiguration=(org.gradle.api.artifacts.Configuration) -> kotlin.Boolean, includeProject=(org.gradle.api.Project) -> kotlin.Boolean, outputFormats=[PNG, SVG], graph=(guru.nidi.graphviz.model.MutableGraph) -> guru.nidi.graphviz.model.MutableGraph)]' with class 'java.util.ArrayList' to class 'org.gradle.api.NamedDomainObjectContainer' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.NamedDomainObjectContainer(com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorExtension$Generator)

**Comment by vanniktech** [comment]
Seems like you configured the `Generator` incorrectly.

**Comment by austince** [comment]
Got this same error with the Firebase example in the readme using 0.6.0-SNAPSHOT.

Other version info:
```
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.10 (AdoptOpenJDK 11.0.10+9)
OS:           Mac OS X 10.15.7 x86_64
```

**Comment by tdp0516** [comment]
I am also getting the above issue with 0.6.0 using the firebase example in the README.
