### ISSUE TITLE
guru.nidi.graphviz.engine.GraphvizException: Initializing graphviz engine took too long.

### ISSUE THREAD

**Issue by mohanvayyala** [vanniktech/gradle-dependency-graph-generator-plugin#119]
Hi, I am working on one of the legacy application which has so many sub projects and all very tightly coupled. Almost all sub modules added into other projects under dependencies and vice versa which can't be avoided .

So the problem here is, when I try to run the **generateDependencyGraph** task it's failing with the below error since in Graphviz.java class it was set to 200 seconds max and in my project due to heavy modules dependency task is taking very long time.
_guru.nidi.graphviz.engine.GraphvizException: Initializing graphviz engine took too long._

Could you please help me to resolve this issue by passing this value as dynamic or any alternative.

Thanks in advance

**Comment by vanniktech** [comment]
This a problem of https://github.com/nidi3/graphviz-java. Please report it over there.
