### ISSUE TITLE
Add image output formats as additional parameters

### ISSUE THREAD

**Issue by Thunderforge** [vanniktech/gradle-dependency-graph-generator-plugin#12]
A `.dot` file, while flexible, is not the most convenient method for sharing. It would be great if this plugin allowed for adding image output.

The `build.gradle` file might look something like this:

```
dependencyGraphGenerator {
    imageFormat = ["png", "jpg"]
}
```

Under the hood, this would be [running `dot -Tps filename.dot -o outfile.XYZ`](https://stackoverflow.com/a/1494495/531762), where XYZ is each of the image extensions provided.

I'm guessing that the default would be no image output.

**Comment by vanniktech** [comment]
That makes sense. We might also want to have a way to specify the folder in which those will be generated into.

**Comment by vanniktech** [comment]
You don't need to share the dot file. It also generates a png file which is located in the root directory. What other formats are you thinking to support?

**Comment by Thunderforge** [comment]
Is generating a png file a new feature? When I was using the plugin, it would only generate the `.dot` file.

**Comment by vanniktech** [comment]
The PNG file is located in the project itself and not under build.

**Comment by Thunderforge** [comment]
Shouldn't the PNG be in build/reports just like the `.dot` file?

**Comment by vanniktech** [comment]
It could be moved there, yes.
