### ISSUE TITLE
broken in gradle 7.0

### ISSUE THREAD

**Issue by NikkyAI** [vanniktech/gradle-dependency-graph-generator-plugin#124]
when runnign with gradle `7.0.2` the task breaks the the following message

```
A problem was found with the configuration of task ':generateDependencyGraph' (type 'DependencyGraphGeneratorTask').
  - Type 'com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorTask' property 'generator' is missing an input or output annotation.
```

**Comment by tdp0516** [comment]
I believe this is a duplicate of this issue: https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/121

It appears to have been fixed but not released yet.

**Comment by vanniktech** [comment]
Yes true.

**Comment by kuldeepsidhu88** [comment]
@vanniktech Has this been released? I am still getting this error in gradle 7.4
