### ISSUE TITLE
Feature Request: Filtering out project dependencies

### ISSUE THREAD

**Issue by davidburstrom** [vanniktech/gradle-dependency-graph-generator-plugin#125]
# Summary

Support a lambda to exclude project dependencies with the `ProjectGenerator`.

# Rationale

In a multi-module project with e.g. a `platform` project, virtually all projects will use it as a dependency, cluttering the graph.
The `includeProject` only filters which depender projects to include in the graph, not the dependee projects.

# Environment

Plugin version 0.6.0.

**Comment by hexun206** [comment]
gradlew generateDependencyGraph
build error:
Execution failed for task ':app:generateDependencyGraph'.
> TypeError: Module.print is not a function

**Comment by vanniktech** [comment]
@davidburstrom can you please try the snapshot with the new changes from @tedliang ?

**Comment by davidburstrom** [comment]
@vanniktech Yes, it works as expected! I'd be happy with a release of this, to avoid depending on snapshot dependencies.

**Comment by vanniktech** [comment]
Nice. Do you think you can come up with a fix for #135 too?
