### ISSUE TITLE
README Firebase example for groovy DSL doesn't seem to work in 0.6.0

### ISSUE THREAD

**Issue by tdp0516** [vanniktech/gradle-dependency-graph-generator-plugin#127]
The firebase example in the README appears to no longer work

import com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPlugin
import com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorExtension.Generator
import guru.nidi.graphviz.attribute.Color
import guru.nidi.graphviz.attribute.Style

plugins.apply(DependencyGraphGeneratorPlugin)

def firebaseGenerator = new Generator(
  "firebaseLibraries", // Suffix for our Gradle task.
  { dependency -> dependency.getModuleGroup().startsWith("com.google.firebase") }, // Only want Firebase.
  { dependency -> true }, // Include transitive dependencies.
  { node, dependency -> node.add(Style.FILLED, Color.rgb("#ffcb2b")) }, // Give them some color.
)

dependencyGraphGenerator {
  generators = [ firebaseGenerator ]
}

I understand that the reason has to do with the new NamedDomainObjectContainer approach and have found online examples. However, I'm having various issues with assigning function parameters to the Generator properties, ie Generator.include

An accurate example in the README would be appreciated in helping diagnosing this problem.

**Comment by fajarnuha** [comment]
indeed, I tried to update the docs here #128

**Comment by vanniktech** [comment]
Thanks for your contirbution @fajarnuha

**Comment by tdp0516** [comment]
@fajarnuha @vanniktech 

Any idea why I'd get an error like this?

Input property 'generator.children' with value 'build_7d9urs4djj01z67sc34y4zhrd$_run_closure5$_closure30$_closure31$_closure33@20e96352' cannot be serialized.

The way I was doing it matches the new doc and I even copy/pasted the doc to make sure I wasn't missing something, but still getting this error.

**Comment by fajarnuha** [comment]
my bad, it seems it can sync and generate the custom task but unable to run the task, probably there is something wrong when assigning lambda function for the extension property in groovy

right now im just forced to use `0.5.0` version

any idea? @vanniktech

**Comment by vanniktech** [comment]
Probably the lambda can't be serialized as an `@Input` would need to look too

**Comment by vanniktech** [comment]
Nope. Feel free to PR, I have very little time for this project unfortunately

**Comment by gradlifier** [comment]
We have the exact same problem as @murat-crvsh and I would appreciate to reopen this issue. I will spend some time to analyze this issue.

**Comment by gradlifier** [comment]
My changes are more of a workaround than a real fix. If I understand the Gradle documentation correctly, all input parameters of a task are supposed to be serializable so that Gradle can detect if a task needs to run or is up-to-date. Therefore, lambda expressions are not allowed at this point. A complete rewrite of the plugin would be necessary to make all parameters of the DependencyGraphGeneratorExtension serializable.

**Comment by xatok** [comment]
Is it possible to use the Firebase example without the usage of lambdas? So at least it can be used until a new version is released. Going back to 0.5.0 is not an option for me since is not compatible with Gradle 7.

**Comment by gradlifier** [comment]
I would be glad having a new (working) version 0.7.0, because currently we must work on a snapshot...

**Comment by vanniktech** [comment]
Would someone mind jumping in as a (replacement) for me? Currently, I don't have the time for this project. Releases are done by pushing a Git tag and everything is automated.

**Comment by vanniktech** [comment]
0.7.0 is released.
