### ISSUE TITLE
runned task with an error

### ISSUE THREAD

**Issue by excitedhaha** [vanniktech/gradle-dependency-graph-generator-plugin#129]
> Task :app:generateDependencyGraph FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDependencyGraph'.
> TypeError: Module.print is not a function

**Comment by pedrofsn** [comment]
Same error here

**Comment by davidburstrom** [comment]
Can you please provide more of the stack trace?

**Comment by davidburstrom** [comment]
Seems quite related to https://github.com/nidi3/graphviz-java/issues/110

**Comment by vanniktech** [comment]
Snapshot is building now with #151 which uses Graphviz 0.18.1 and hence this issue should be closed. I'll cut a release in a few days, in the meantime please use the SNAPSHOT.
