### ISSUE TITLE
gradlew generateDependencyGraph build error

### ISSUE THREAD

**Issue by hexun206** [vanniktech/gradle-dependency-graph-generator-plugin#130]
gradlew generateDependencyGraph
build error:
Execution failed for task ':app:generateDependencyGraph'.
TypeError: Module.print is not a function

**Comment by lennart-bos** [comment]
Same here, completely broken, tried with both Gradle 5.6.1 and 6.9.1... :(

**Comment by zsperske** [comment]
I also experienced the same error, it appears it may be an out of memory issue.

**Comment by vanniktech** [comment]
Snapshot is building now with #151 which uses Graphviz 0.18.1 and hence this issue should be closed. I'll cut a release in a few days, in the meantime please use the SNAPSHOT.
