### ISSUE TITLE
0.6 does not work with custom task

### ISSUE THREAD

**Issue by hrach** [vanniktech/gradle-dependency-graph-generator-plugin#131]
As mentioned here, it fails to launch the custom task:
https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/127#issuecomment-876729751

**Comment by vanniktech** [comment]
Snapshot is building now with #151 which uses Graphviz 0.18.1 and hence this issue should be closed. I'll cut a release in a few days, in the meantime please use the SNAPSHOT.

This might also actually be fixed with 0.7.0
