### ISSUE TITLE
Stackoverflow error

### ISSUE THREAD

**Issue by TalhaMFP** [vanniktech/gradle-dependency-graph-generator-plugin#132]
Running into a StackOverflow error when running generateDependencyGraph task. Using version 0.6.0

Execution failed for task ':generateDependencyGraph'.
> java.lang.StackOverflowError

**Comment by davidburstrom** [comment]
@TalhaMFP That is too little information to deduce what the issue can be. Can you provide more data, please?

**Comment by vanniktech** [comment]
Snapshot is building now with #151 which uses Graphviz 0.18.1 and hence this issue should be closed. I'll cut a release in a few days, in the meantime please use the SNAPSHOT.
