### ISSUE TITLE
Java application UI is created when generating a graph

### ISSUE THREAD

**Issue by davidburstrom** [vanniktech/gradle-dependency-graph-generator-plugin#135]
On macOS, whenever a graph is generated, the `java` application shows up in the dock, and remains there until the Gradle daemon is killed, or until the application is closed (which kills the Gradle daemon). This is rather annoying, especially if you'd like to keep your applications tidy.

It only happens if the list of output formats only includes `guru.nidi.graphviz.engine.Format.PNG` and `Graphviz.render` is executed.

This happens with 0.6.0 and 0.7.0-SNAPSHOT.

**Comment by davidburstrom** [comment]
I've tried to provide graphviz versions up to and including 0.8.5 but it behaves the same. With 0.8.6 and up, the API to `render` has changed, so I haven't looked further.

**Comment by davidburstrom** [comment]
@vanniktech I did some further experimentation and found that the bug was fixed between Graphviz 0.16.1 and 0.16.2. It is reproducable by executing `./gradlew test --tests=com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPluginTest.integrationTestGradle50` on macOS.

I'd be happy to see someone else do the actual bump because it's more to it than just increasing the version number. Possibly even straight to 0.18.1, while at it.

**Comment by davidburstrom** [comment]
Likely fixed in Graphviz by https://github.com/nidi3/graphviz-java/commit/0088c5da009234059e1b7a737b7c774f10405f74

**Comment by vanniktech** [comment]
Bumping to 0.18.1 sounds good!

**Comment by vanniktech** [comment]
Snapshot is building now with #151 which uses Graphviz 0.18.1 and hence this issue should be closed. I'll cut a release in a few days, in the meantime please use the SNAPSHOT.
