### ISSUE TITLE
Where can I see dependency pictures

### ISSUE THREAD

**Issue by ff-frida** [vanniktech/gradle-dependency-graph-generator-plugin#139]
I executed [generatedependencygraph] without any error prompt, [task execution finished ': generateprojectdependencygraph'.]. Where can I view the graph

mac os 
android studio fox
gradle         classpath 'com.android.tools.build:gradle:3.6.0'

**Comment by vanniktech** [comment]
It's inside the build/reports folder

**Comment by ff-frida** [comment]
> It's inside the build/reports folder

thanks
