### ISSUE TITLE
Execution failed "TypeError: Module.print is not a function" for a mono repo

### ISSUE THREAD

**Issue by LartyHD** [vanniktech/gradle-dependency-graph-generator-plugin#144]
```
> Task :generateDependencyGraph
Warning: Nashorn engine is planned to be removed from a future JDK release

> Task :generateDependencyGraph FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateDependencyGraph'.
> TypeError: Module.print is not a function
```

It doesn't matter if I use the 0.8.0-SNAPSHOT or 0.7.0.
Any idea on how to fix that?

**Comment by vanniktech** [comment]
Probably graphviz needs an update on our site. Feel free to PR:

https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/master/build.gradle#L71

**Comment by pallavahooja** [comment]
Any solution for this? I am also facing same issue

**Comment by vanniktech** [comment]
Tests are failing here: https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/pull/145
