### ISSUE TITLE
does not apply my custom generator

### ISSUE THREAD

**Issue by AdriaBergeAguilar** [vanniktech/gradle-dependency-graph-generator-plugin#146]
it is a project with many modules internally with relationship between them

I have added the dependency,
I have adapted the firebase configuration so that it is only for my projects and subprojects. I want to be able to reduce the number of nodes generated by the default generator.

my config

plugins{
    id 'com.vanniktech.dependency.graph.generator' version '0.7.0'
}

plugins.apply(DependencyGraphGeneratorPlugin)

dependencyGraphGenerator {
    generators {
         fwk {
            include = { dependency -> dependency.getModuleGroup().startsWith("${group}") } // Only want FWK.
            children = { dependency -> false } // Include transitive dependencies.
            dependencyNode = { node, dependency -> node.add(Style.FILLED, Color.rgb("#3511A3")) } // Give them some color.
        }
    }
}

I use intellij and as a detail the IDE tells me that FWK is disabled, as it does not detect that command. I don't know if this is normal behavior or if it is already an indicator of problems.

Thenks

**Comment by vanniktech** [comment]
Which tasks did you try to run?

**Comment by vanniktech** [comment]
I think you just need to run the `generateDependencyGraphFwk` task which will generate the graph. And then inside the build directory, you'll find your images
