### ISSUE TITLE
Print all generated files path

### ISSUE THREAD

**Issue by SimonMarquis** [vanniktech/gradle-dependency-graph-generator-plugin#155]
This would be helpful to open the svg/png/dot file once generated with a simple clic instead of navigating to the right directory (and to know where to look).
I thought about adding such log with `logger.lifecycle()` which could be silenced with `-q` if needed.
WDYT?

**Comment by vanniktech** [comment]
Yes very much. And ideally, we'd print one line for each extension (dot, png, svg)
