### ISSUE TITLE
Mention generateProjectDependencyGraph in README

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/gradle-dependency-graph-generator-plugin#156]
Most people probably don't know this exists

**Comment by SimonMarquis** [comment]
I'd love to take this one as well.
I have one request for you: could you run both `generateDependencyGraph` and `generateProjectDependencyGraph` on your private [chess clock app](https://play.google.com/store/apps/details?id=com.vanniktech.chessclock)/
It you be great to add them both in the readme like this:

---

## Usage

By default, this plugin provides two reporting tasks:

| `generateDependencyGraph`                                                  | `generateProjectDependencyGraph`                                                                  |
|----------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| Generates a **complete** dependency graph in `build/reports/dependency-graph/` | Generates a dependency graph of the **project modules** in `build/reports/project-dependency-graph/` |
| ![Dependency Graph](dependency-graph.png)                                  | ![Project Dependency Graph](project-dependency-graph.png)                                         |

The graphs are generated in `.png`, `.svg` & `.dot` format.
_Source: [chess clock app](https://play.google.com/store/apps/details?id=com.vanniktech.chessclock)_

There are extension points to be able to generate graphs which only include some dependencies and their transitive ones. The trick is to hook a [Generator](./src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt) in over the `dependencyGraphGenerator` extension. Note that this is extremely experimental and will likely change between releases. It's still fun though.

---

WDYT?

**Comment by vanniktech** [comment]
Really good. I'd use an open source project instead though: https://github.com/vanniktech/Emoji/pull/846

**Project dependency graph:**

![project-dependency-graph](https://user-images.githubusercontent.com/5759366/172049529-c700f4d3-6412-4345-bdc0-f60fb8fc2cfc.png)

![project-dependency-graph](https://user-images.githubusercontent.com/5759366/172049523-eb29a489-7fd0-4f95-8d31-c4098feb0bdd.svg)

**Dependency graph:**

![dependency-graph](https://user-images.githubusercontent.com/5759366/172049543-76711865-6a0c-45d1-b7fe-312afcb3e5bd.png)

![dependency-graph](https://user-images.githubusercontent.com/5759366/172049547-988ba7e5-6c49-415a-b921-9b7c7907a2fe.svg)

----

*Generated those with version 0.7.0*

**Comment by SimonMarquis** [comment]
Yeah, it's better to use a public project 👍
Could you render them with the 100dpi? Otherwise I'll do it myself since I have the snapshot locally.

**Comment by SimonMarquis** [comment]
Although I guess it's preferable to embed the SVG rather than the png on the README file.

**Comment by vanniktech** [comment]
Can't we use the SVG file for the README? (it's the 2nd one)

**Comment by SimonMarquis** [comment]
It's almost ready, but I think we should also do the same for the custom generator.
Though there is no firebase dependencies in it, maybe we could replace this with an AndroidX generator?

**Comment by vanniktech** [comment]
Yeah AndroidX sounds good!

**Comment by SimonMarquis** [comment]
I'll try to run it locally now that https://github.com/vanniktech/Emoji is using this plugin :)

**Comment by SimonMarquis** [comment]
AndroidX feels overwhelming, and kind of broken? (is it because other modules does not depend on them directly? api vs implementation ?)
![dependency-graph-android-x-libraries](https://user-images.githubusercontent.com/1921278/172051194-85143a1f-50ac-4529-a37e-318b25678e17.svg)

Filtering on Jetbrain's feels better to me
![dependency-graph-jetbrains-libraries](https://user-images.githubusercontent.com/1921278/172051247-3c829de0-1624-4e65-8cb9-94fa61b07c65.svg)

**Comment by vanniktech** [comment]
Yes Jetbrains is awesome! Can we change the color though?  Maybe some kind of red/purple tone?

<img width="142" alt="Screen Shot 2022-06-05 at 15 15 53" src="https://user-images.githubusercontent.com/5759366/172052328-54c65569-dbd2-40e2-a4c2-0a3aa0a1dd23.png">

**Comment by vanniktech** [comment]
> (is it because other modules does not depend on them directly? api vs implementation ?) Or is it a bug?

Would need to look at it. Been quite a while since I wrote the mechanism for the mapping. `emoji-ios` have an `api project(":emoji")` which might cause it to be displayed like this and then I'd say this graph looks good.

**Comment by SimonMarquis** [comment]
I've gone with their purple color `#AF1DF5` https://www.jetbrains.com/company/brand/#logos-and-icons:~:text=%23FF45ED-,%23AF1DF5,-%236B57FF
