### ISSUE TITLE
Increase default dpi of graphviz rendering

### ISSUE THREAD

**Issue by SimonMarquis** [vanniktech/gradle-dependency-graph-generator-plugin#158]
The default rendering does not feel crisp at all.
Could we bump it a little bit?
100dpi seems good enough to me.

| Default `72dpi` (1074x332) | `100dpi` (1492x461) | `200dpi` (2985x922) |
|---|---|---|
| ![dependency-graph](https://user-images.githubusercontent.com/1921278/172026637-f8ff38e1-efb4-4d73-9f89-92b8b75702c4.png) | ![dependency-graph](https://user-images.githubusercontent.com/1921278/172026671-ca48c9f4-5c95-4384-9c83-ec83413d5f07.png) | ![dependency-graph](https://user-images.githubusercontent.com/1921278/172026723-d1c491a1-81b4-45c9-885b-7a38c19e7b11.png) |

It seems the default comes from here:

https://github.com/nidi3/graphviz-java/blob/f0c1fdfa37c8b9876ef1dcccec1a6c19219e727e/graphviz-java/src/main/java/guru/nidi/graphviz/attribute/validate/AttributeConfigs.java#L66

And here as well:
https://github.com/nidi3/graphviz-java/blob/f0c1fdfa37c8b9876ef1dcccec1a6c19219e727e/graphviz-java/src/main/java/guru/nidi/graphviz/engine/ProcessOptions.java#L25

**Comment by SimonMarquis** [comment]
Default dpi value seems to be 96 on the official [graphviz documentation](https://graphviz.org/docs/attrs/dpi/).

**Comment by vanniktech** [comment]
Yeah let's use 100. In the past if I wanted high resolution, I've used exclusively

**Comment by SimonMarquis** [comment]
100 or the "official" default of 96? it's your call.

**Comment by vanniktech** [comment]
I like your 100
