### ISSUE TITLE
Customize links between nodes

### ISSUE THREAD

**Issue by SimonMarquis** [vanniktech/gradle-dependency-graph-generator-plugin#169]
Would you be open to allow customizing links between nodes?
We might want to highlight a specific path, or a specific dependency type, similarly to `dependencyNode` and `projectNode`.

https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/104abbdb1cc0c689688f665d5cc27b5b3649bb4a/src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt#L62-L65

**Comment by vanniktech** [comment]
Yep sure.

**Comment by vanniktech** [comment]
Waiting for this and then I'll do a new release 0.8.0. No rush though
