### ISSUE TITLE
Modules added as test dependencies are skipped

### ISSUE THREAD

**Issue by mustafaozhan** [vanniktech/gradle-dependency-graph-generator-plugin#200]
Hello i just start using the generator and relised that the modules that used in test are ignored.

I am getting below picture
<img width="1315" alt="Screenshot 2022-10-31 at 20 52 47" src="https://user-images.githubusercontent.com/30001999/199086960-0929dafb-ad79-4974-a7d3-bd3e6aa3c5b8.png">

Where my dependency graph should be like in the README.md of the [repo](https://github.com/Oztechan/CCC)

Please pay attention to `test` module which is added as test dependency to many other module.

**Comment by vanniktech** [comment]
Also on purpose. https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/c39c8538877670c219da7dd58f5dc2ca88319efa/src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt#L77

Can you try using the API to create your own graphs? https://github.com/vanniktech/gradle-dependency-graph-generator-plugin#generator-example that should solve everything for you

**Comment by mustafaozhan** [comment]
Hello sorry for late reply, I think that works now, thank you!
