### ISSUE TITLE
Setup dependency

### ISSUE THREAD

**Issue by Kaaveh** [vanniktech/gradle-dependency-graph-generator-plugin#213]
Unfortunately, I don't figure out how to set up this library in [my project](https://github.com/Kaaveh/ComposeNews). Could you explain how to add it in KTS gradle files?

**Comment by vanniktech** [comment]
It's in the README

**Comment by Kaaveh** [comment]
Yes, But I don't figure out how to place it in my root gradle file. It's like:

```kotlin
plugins {
    id("com.android.application") version "7.4.0" apply false
    id("com.android.library") version "7.4.0" apply false
    id("org.jetbrains.kotlin.android") version "1.7.0" apply false
    id("com.google.dagger.hilt.android") version "2.44.2" apply false
}
```
