### ISSUE TITLE
Consider using graphviz-java instead of dot

### ISSUE THREAD

**Issue by jacobilsoe** [vanniktech/gradle-dependency-graph-generator-plugin#23]
Consider using [graphviz-java](https://github.com/nidi3/graphviz-java) so you don't have to install dot locally.

**Comment by vanniktech** [comment]
Oh that looks quite cool. This would be for sure better than what we're doing now. Want to take a stab at this and implement it?

**Comment by jacobilsoe** [comment]
Yep, when I get some time, I'll take a look at it.

**Comment by vanniktech** [comment]
Have you had time to look into this yet? I've wanted to wait with the 0.4.0 release for this.

**Comment by jacobilsoe** [comment]
No, I got busy with other stuff. :disappointed: I think you better make the release and postpone this issue for a future release.

**Comment by vanniktech** [comment]
I'll tackle this and then release 0.4.0

**Comment by jacobilsoe** [comment]
Very nice! Thanks.

**Comment by vanniktech** [comment]
I'll need to see whether I can squeeze out 0.5.0 later or next week.
