### ISSUE TITLE
Only generate dependency graphs between modules and modules, not libraries/aar/jar

### ISSUE THREAD

**Issue by matrixxun** [vanniktech/gradle-dependency-graph-generator-plugin#24]
Hi vanniketch
It's very cool plugin.
Because my android project is a multi-module project，so I just want to generate dependency graphs between local modules and modules, not library or aar from remote repositories such as : 
`api 'com.google.android.instantapps:instantapps:1.1.0'`
What should I do？
The following figure is my project structure：
![c539a161-7da1-4742-b7d2-ab73c022cc11 1](https://user-images.githubusercontent.com/2074894/37460073-10b749a2-2885-11e8-8cfd-050acee96a5b.png)

**Comment by vanniktech** [comment]
This should be doable by using the Generator API. Look at the README for an example.

**Comment by matrixxun** [comment]
@vanniktech, I found that you use code:
`dependency -> dependency.getModuleGroup().startsWith("xxx.xxx.xxx") ` to just generate firebase dependency in your project and It's work well in my test.
because I am not familiar with kt and groovy language, so would you help me to provide sample code to reach my goal.

**Comment by vanniktech** [comment]
I'll think about an example and try to come up with something.

**Comment by matrixxun** [comment]
Thanks.
I found ResolvedDependency API `getModuleName` can realize my todo. Just write like this `dependency.getModuleName().startsWith("Module") || dependency.getModuleName().startsWith("Module")`
It's cool.
![07d0764b-0d72-44d7-a56b-a58c88a80451 1](https://user-images.githubusercontent.com/2074894/37466523-edbb0772-2898-11e8-9c5e-b129ea32cf27.png)

**Comment by vanniktech** [comment]
Yes you can use that one. Can this be closed then?

**Comment by matrixxun** [comment]
yes, you can close it.

**Comment by zawadz88** [comment]
In case anyone here was looking for a solution to this problem but don't have module suffixes as in the original question I'm posting my solution.

In your root project `build.gradle`:


```
buildscript {
  repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
  }
  dependencies {
    classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.6.0-SNAPSHOT"
  }
}

//...

import com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPlugin
import com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorExtension.Generator
import guru.nidi.graphviz.attribute.Color
import guru.nidi.graphviz.attribute.Style

plugins.apply(DependencyGraphGeneratorPlugin)

def customGenerator = new Generator(
        "custom", // Suffix for our Gradle task.
        { dependency ->
            dependency.getName().startsWith("you-root-project-name") }, // Only want project modules.
        { dependency -> true }, // Include transitive dependencies.
        { node, dependency ->
            def color = dependency.getName().toLowerCase().contains("test") ? "#7BAC2B" : "#5BA2FF" // use in case your test modules contain "test" and you want to have them in a different color
            node.add(Style.FILLED, Color.rgb(color))
        }, // Give them some color.
        { node, _ -> node },
        null,
        { it.name.toLowerCase().contains("compileClassPath".toLowerCase()) // use if you want to have test modules included as well }
)

dependencyGraphGenerator {
    generators.add(customGenerator)
}
```
You'll need to replace `"you-root-project-name"` with you actual project name.
then in the command line:
```
./gradlew generateDependencyGraphCustom
```

I tested this with Gradle 5.3.1 and Android Gradle Plugin 3.4.1
