### ISSUE TITLE
Where is the generated png file?

### ISSUE THREAD

**Issue by matrixxun** [vanniktech/gradle-dependency-graph-generator-plugin#25]
after executing tasksgenerateDependencyGraph, I found a file named dependency-graph.dot in `./build/`
![880970b7-0335-4167-8008-6d8027119cb8](https://user-images.githubusercontent.com/2074894/37466898-d816ec14-2899-11e8-814e-b7d73edd633a.png)
Where is png file?
My PC use Windows10

**Comment by vanniktech** [comment]
It's in the root directory of your project.

**Comment by matrixxun** [comment]
you are right. please close it

**Comment by vanniktech** [comment]
#12 will do even more
