### ISSUE TITLE
Dependencies aren't showing up between project modules

### ISSUE THREAD

**Issue by MatthewPageCS** [vanniktech/gradle-dependency-graph-generator-plugin#28]
I might be missing something about how to use this library, so I made a sample project here:
https://github.com/MatthewPageCS/SampleModuleProject

The code related to the plugin is in the project level build.gradle:
https://github.com/MatthewPageCS/SampleModuleProject/blob/master/build.gradle

Here is the resulting image: https://github.com/MatthewPageCS/SampleModuleProject/blob/master/dependency-graph-modules.png?raw=true

This is pretty incorrect, as app depends on all of feature-one, feature-two, and feature-three, and the feature modules depend on lib, models, and networking. None of these dependencies are expressed in the graph. The boxes also don't have any color, like the example in the README of the plugin's repo.

Am I missing something, or is there a bug in the plugin?

**Comment by vanniktech** [comment]
This is something that can be improved yes. If you generate an entire graph you'll see that your modules are being listed twice in the graph. I haven't found a way to relate a Project to a ResolvedDependendcy. 

I'll take a look at your custom generator later.

**Comment by vanniktech** [comment]
If you apply this patch file:

```diff
diff --git a/build.gradle b/build.gradle
index 24963ec..31611d2 100644
--- a/build.gradle
+++ b/build.gradle
@@ -33,7 +32,7 @@ plugins.apply(DependencyGraphGeneratorPlugin)
 def moduleGenerator = new Generator(
         "modules", // Suffix for our Gradle task.
         "", // Root suffix that we don't want in this case.
-        { dependency -> dependency.getModuleGroup().startsWith("xyz.matthewpage") }, // Only want Firebase.
+        { dependency -> dependency.getModuleGroup().startsWith("xyz.matthewpage") || dependency.getModuleGroup().startsWith("SampleModule") }, // Only want Firebase.
         { dependency -> true }, // Include transitive dependencies.
         { dependency -> new GraphFormattingOptions(Shape.BOX, Style.FILLED, Color.fromRgb(255, 203, 43)) }, // Give them some color.
 )
```

you'll get a generated image that looks like this:

![dependency-graph-modules](https://user-images.githubusercontent.com/5759366/37555624-bbc1beb6-29ea-11e8-85bd-24ca4b39ae8b.png)

While it is better and shows the modules it also highlights the problem that your modules are included twice. This is what I was referring to earlier.

I'd need to find a way to map `it.resolvedConfiguration.firstLevelModuleDependencies` to a `project` in here - https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/67cd9091c3876641ef492870c0581c8adc28136b/src/main/kotlin/com/vanniktech/dependency/graph/generator/DotGenerator.kt

I haven't found one yet. If you do please let me know.
