### ISSUE TITLE
Error while creating custom plugin 

### ISSUE THREAD

**Issue by xanderblinov** [vanniktech/gradle-dependency-graph-generator-plugin#46]
Hi, @vanniktech and thank you for a awesome plugins. 

I tried to implement custom plugin from example and got and error
```groovy
unable to resolve class com.vanniktech.dependency.graph.generator.dot.Shape
 @ line 5, column 1.
   import com.vanniktech.dependency.graph.generator.dot.Shape
   ^
```
It looks like .gradle file doesn't see dependencies
The question is, how to properly show dependencies to a lib for a .gradle files?

**Comment by vanniktech** [comment]
Interesting, can you show me some more information? Which version are you using?

**Comment by xanderblinov** [comment]
`
       classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.4.0"
`

**Comment by xanderblinov** [comment]
for more information:

1) I've just copy-past  code of Firebase example to .gradle file located at root_dir/scripts/

2) ./gradlew generateDependencyGraph works perfect

**Comment by xanderblinov** [comment]
<img width="952" alt="screen shot 2018-05-02 at 15 14 02" src="https://user-images.githubusercontent.com/469876/39523410-2a54d8de-4e1e-11e8-999d-d52d764343df.png">


my top level build.gradle snippet with integration:
```groovy
buildscript {
    ext.kotlin_version = '1.2.31'
    repositories {
        google()
        jcenter()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.4.0"
    }
}

apply plugin: "com.vanniktech.dependency.graph.generator"

apply from: "scripts/dependecies-modules.gradle"
```

**Comment by xanderblinov** [comment]
@vanniktech could you provide step-by-step Custom plugin installation guide, please. Maybe it helps me to find an error and prevent it for other users

**Comment by xanderblinov** [comment]
I found solution but it too dirty: place code of your custom plugins to root build.gradle file

Maybe you know another way?

**Comment by vanniktech** [comment]
Cool, glad you got it working.
