### ISSUE TITLE
Could you support displaying library version code in report PNG file.

### ISSUE THREAD

**Issue by matrixxun** [vanniktech/gradle-dependency-graph-generator-plugin#48]
If my library is from maven/jcenter，could you display the aar version code?
![image](https://user-images.githubusercontent.com/2074894/40219539-7259dd1e-5aa8-11e8-8830-b7492f118093.png)

**Comment by vanniktech** [comment]
You can also do that using the latest `0.5.0-SNAPSHOT` and the Generator api. You need to use the `val dependencyNode: (MutableNode, ResolvedDependency) -> MutableNode = { node, _ -> node },` in which you can give your node a custom label and get the label from the Gradle ResolvedDependency.
