### ISSUE TITLE
[Feature request] Can we export the dependency graph to svg ?

### ISSUE THREAD

**Issue by gengjiawen** [vanniktech/gradle-dependency-graph-generator-plugin#50]
I am not falimar with `Graphviz`, is this possible ?

**Comment by gengjiawen** [comment]
The reason I want svg is that svg is better than png in view (especially the scale part) and size part.

**Comment by gengjiawen** [comment]
I checked the code, it looks like doable. Can we make it a default option or configurable ?

**Comment by vanniktech** [comment]
Have a look at #51
