### ISSUE TITLE
NumberFormatException when checking Nashorn version in graphviz-java

### ISSUE THREAD

**Issue by NikkyAI** [vanniktech/gradle-dependency-graph-generator-plugin#58]
I have tried this plugin on a complex multi-module gradle project of mine to try to see and simplify cross relations

this is the the error I encounter:
https://scans.gradle.com/s/2mi5wh2ir3iz4

this seems to be related to https://github.com/nidi3/graphviz-java/issues/69

**Comment by vanniktech** [comment]
Yes. Unfortunately it needs to be fixed there.
