### ISSUE TITLE
Export plugin configuration to separate gradle file.

### ISSUE THREAD

**Issue by carlosmuvi** [vanniktech/gradle-dependency-graph-generator-plugin#63]
First of all, thanks for creating this plugin! Works perfectly.

I'm using a custom `Generator`, and since that adds a couple more lines to the Gradle file I was trying to export all your plugin configuration to a separate `dependency-graph.gradle` file to clean it up a bit.

However, imports cannot be resolved if you're not in the main gradle file.

Any ideas how to achieve this? 

Thanks again!

**Comment by vanniktech** [comment]
Yes. I've also had that problem. It's due to https://discuss.gradle.org/t/buildscript-configurations-classpath-not-available-in-apply-from-scripts/1391

The workaround is the following inside `graphs.gradle.kts`:

```kotlin
buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath("com.vanniktech:gradle-dependency-graph-generator-plugin:0.5.0")
  }
}

import com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPlugin

rootProject.plugins.apply(DependencyGraphGeneratorPlugin::class.java)
```

**Comment by carlosmuvi** [comment]
Works perfectly. Thanks!
