### ISSUE TITLE
Issue when launching the task

### ISSUE THREAD

**Issue by manuel-sejourne** [vanniktech/gradle-dependency-graph-generator-plugin#64]
Hi ! I have this issue 

Execution failed for task ':mobile:generateDependencyGraph'.
> For input string: "152-release"

Do you have a fix ?

**Comment by vanniktech** [comment]
Yes. It's been fixed already with https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/pull/60

The workaround for now is:

```gradle
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "guru.nidi:graphviz-java:0.5.3"
    classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.5.0"
  }
}
```
