### ISSUE TITLE
can not configure this in  `~/.gradle/init.gradle`

### ISSUE THREAD

**Issue by jiahut** [vanniktech/gradle-dependency-graph-generator-plugin#68]
I config this plugin  in  `~/.gradle/init.gradle`:

```
initscript {
    repositories {
    mavenCentral()
    }
    dependencies {
    classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.5.0"

    }
}
rootProject {
    apply plugin: "com.vanniktech.dependency.graph.generator"
}
```

whith in gradle project, it report : 

`Task 'generateDependencyGraph' not found in root project  xxx .`

**Comment by vanniktech** [comment]
I've never used `init.gradle` What's the approach here?

In normal projects it works normally. Might be due to a new mechanism that's not supported.

**Comment by jiahut** [comment]
@vanniktech  the `init.gradle` works with plugin `  apply plugin: com.dorongold.gradle.tasktree.TaskTreePlugin
`

**Comment by vanniktech** [comment]
This is as good as saying cucumbers can be cut. It does not give me any information. Can you give me some more information?

**Comment by vanniktech** [comment]
You gotta do it like this:

```gradle
import com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPlugin

initscript {
  repositories {
   mavenCentral()
  }
  dependencies {
    classpath "com.vanniktech:gradle-dependency-graph-generator-plugin:0.5.0"
  }
}
rootProject {
  plugins.apply(DependencyGraphGeneratorPlugin)
}
```

Then it works without any problems. Your approach should work too but seems like Gradle is having a bug there.
