### ISSUE TITLE
Plugin apply to subproject in multiproject build

### ISSUE THREAD

**Issue by tfedyanin** [vanniktech/gradle-dependency-graph-generator-plugin#69]
I have multiproject build with structure:
project Main
| --> project IntegrationTestsSubproject
I use 'apply plugin' only in main project, but when I generate graph I see only my subproject with dependencies

**Comment by vanniktech** [comment]
Can you give some more information? I don't understand your issue.

**Comment by tfedyanin** [comment]
After debugging i found this:
`    val projects = (if (project.subprojects.size > 0) project.subprojects else setOf(project))
        .filter { generator.includeProject(it) }`
Why used only subproject, but root project ignored?
Moreover, if it needed to apply plugin for many projects then used subproject section, java plugin for example.
It may be worth documenting this behaviour or simplify it

**Comment by vanniktech** [comment]
Oh because I usually don't have root projects where you have actual dependencies.

**Comment by tfedyanin** [comment]
I change this code to ` val projects = setOf(project)` for test and apply your plugin in `allprojects {}` section in root project. All working fine, in every project (include root project) created graph in build directory. 
I think this approach is more flexible and convenient.
Can I create a requester if you agree?

P.S. Thank you for plugin, it's wonderful tool

**Comment by vanniktech** [comment]
Thought about this again and it's very weird that you have a root project where you actually have dependencies and code. 

Can't you do subprojects / allprojects and then apply the plugin? That way I don't think you'd need to change anything in this plugin.

Also, note that you can exclude certain projects with the Extension API.

Hence I'm closing this.

**Comment by dagguh** [comment]
> it's very weird that you have a root project where you actually have dependencies and code

We have a [project with dependencies](https://bitbucket.org/atlassian/jira-performance-tests/) and I don't find anything weird about it.
