### ISSUE TITLE
GenerateDependencyGraph task generates png with single app block (for project with flavors)

### ISSUE THREAD

**Issue by AlexKorovyansky** [vanniktech/gradle-dependency-graph-generator-plugin#7]
I have a AS 3.0 / Kotlin 1.2.21 / gradle 4.1 project with multiple dependencies with classical root and app project modules structure. Full list of dependencies:

```gradle
dependencies {
    kapt "com.github.hotchemi:permissionsdispatcher-processor:3.1.0"
    kapt "com.hannesdorfmann.fragmentargs:processor:$fragmentArgs_version"
    kapt "com.github.bumptech.glide:compiler:$glide_version"
    kapt "com.google.dagger:dagger-compiler:$dagger_version"
    kapt "nz.bradcampbell:paperparcel-compiler:$paperparcel_version"

    compileOnly 'org.glassfish:javax.annotation:10.0-b28'

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':sinch-android-rtc-3.12.3')
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.0@aar') {
        transitive = true
    }
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "com.squareup.okhttp3:okhttp:$okHttp_version"
    implementation "com.squareup.okhttp3:logging-interceptor:$okHttp_version"
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit_version"
    implementation "com.android.support:appcompat-v7:$support_version"
    implementation "com.android.support:recyclerview-v7:$support_version"
    implementation "com.android.support:customtabs:$support_version"
    implementation "com.android.support:design:$support_version"
    implementation "com.android.support:support-dynamic-animation:$support_version"
    implementation "com.google.android.gms:play-services-maps:$playServices_version"
    implementation "com.google.android.gms:play-services-location:$playServices_version"
    implementation "com.google.android.gms:play-services-places:$playServices_version"
    implementation "com.google.android.gms:play-services-gcm:$playServices_version"
    implementation "com.google.firebase:firebase-core:$playServices_version"
    implementation "com.google.firebase:firebase-messaging:$playServices_version"
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.1.0'
    implementation "com.github.bumptech.glide:glide:$glide_version"
    implementation 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT'
    implementation 'com.jakewharton.timber:timber:4.6.0'
    implementation "com.google.dagger:dagger:$dagger_version"
    implementation "org.igniterealtime.smack:smack-android-extensions:$smack_version"
    implementation "org.igniterealtime.smack:smack-tcp:$smack_version"
    implementation 'de.hdodenhof:circleimageview:2.1.0'
    implementation "nz.bradcampbell:paperparcel:$paperparcel_version"
    implementation "nz.bradcampbell:paperparcel-kotlin:$paperparcel_version"
    implementation 'com.hannesdorfmann:adapterdelegates2:2.0.1'
    implementation 'org.apmem.tools:layouts:1.10@aar'
    implementation "com.hannesdorfmann.fragmentargs:annotation:$fragmentArgs_version"
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
    implementation "com.daimajia.swipelayout:library:1.2.0@aar"
    implementation 'com.facebook.rebound:rebound:0.3.8'
    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation 'com.github.chrisbanes:PhotoView:2.1.3'
    implementation 'com.android.support:multidex:1.0.2'
    implementation 'com.hannesdorfmann.mosby3:mvp:3.0.4'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.facebook.android:facebook-login:[4,5)'
    implementation 'com.romandanylyk:pageindicatorview:0.2.0@aar'
    implementation "com.github.hotchemi:permissionsdispatcher:3.1.0"
    implementation 'cn.aigestudio.wheelpicker:WheelPicker:1.1.2'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.5'
    releaseImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.12.0'
    testImplementation 'com.squareup.leakcanary:leakcanary-android-no-op:1.5'

    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
}
```

After running of ./gradlew :app:generateDependencyGraph, plugin outputs 
[this graph](https://user-images.githubusercontent.com/479961/36989896-3cd91f02-20cd-11e8-89ce-68062b867ebd.png), which has only app element.

I've tried to use 0.1.0 and 0.2.0-SNAPSHOT, the described issue happens for both of them.

**Comment by AlexKorovyansky** [comment]
FYI, the project has two signingConfigs: debug and release, two build types: debug and release, and three productFlavors: dev, qa, and production. Let me know if you have any other info to resolve the issue.

**Comment by vanniktech** [comment]
Flavors are the reasons it won't work. Currently we only get compileClassPath, debugCompileClassPath and releaseCompileClassPath. I left a todo in DotGenerator about this. 

Would you like to see one graph with all flavors or per flavors based graphed?

**Comment by vanniktech** [comment]
You can play around with it that way. Execute publishToMavenLocal task and in your app use mavenLocal() instead snapshot repository to use the local version.

**Comment by AlexKorovyansky** [comment]
> Would you like to see one graph with all flavors or per flavors based graphed?
In our case, we have the same list of dependencies for all flavors, so both options will work. Thinking about generic case, I believe that should be customizable via the task parameter.

**Comment by AlexKorovyansky** [comment]
> You can play around with it that way. Execute publishToMavenLocal task and in your app use mavenLocal() instead snapshot repository to use the local version.

What do you mean exactly?

**Comment by vanniktech** [comment]
The concrete problem lies [here](https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/fc6512e42257921c32b490515221f4d775d93aae/src/main/kotlin/com/vanniktech/dependency/graph/generator/DotGenerator.kt#L50). If your flavor is called `free` then there should be a `debugFreeCompileClasspath` which won't be filtered through.

Just matching `debug` & `CompileClasspath` wont work though since there's also `debugUnitTestCompileClasspath` which you probably don't want too match.

In general the problem is slightly bigger since you also might want to generate a dependency graph for all of your tests. So being able to plugin the path you want to have a graph for seems like a good solution.

---

You could - in order to create a graph for you app - fork this repo and edit the if check to also include your flavors. Then use `./gradlew publishToMavenLocal` to publish the repo into your local maven folder and in your app you can use `mavenLocal()` instead of the snapshot repository url and test your changes.

**Comment by vanniktech** [comment]
Got an idea how to solve this and I'll try it later.

**Comment by canberkozcelik** [comment]
I've actually tried this since my project has some flavors too, 
added `it.name == "debugDevFlavorCompileClasspath"`

> You could - in order to create a graph for you app - fork this repo and edit the if check to also include your flavors. Then use ./gradlew publishToMavenLocal to publish the repo into your local maven folder and in your app you can use mavenLocal() instead of the snapshot repository url and test your changes.

but having the following error from generate task:
Error:Execution failed for task ':generateDependencyGraph'.
> org.gradle.process.ExecSpec.setExecutable(Ljava/lang/String;)V

**Comment by vanniktech** [comment]
Which Gradle version are you using? Might be that `setExecutable` isn't there yet. I'm using Gradle 4.6

**Comment by canberkozcelik** [comment]
Yes, that might be the reason, I'm using 2.3.3 since it's an old project and I'm too lazy to upgrade its gradle, thanks

**Comment by vanniktech** [comment]
Oh yes that's quite old. You should upgrade Gradle though it has gotten a lot better and also faster.

**Comment by canberkozcelik** [comment]
I'm sorry it was tools plugin the version is 3.3 but still old, I'll try 4.6 though

**Comment by vanniktech** [comment]
SNAPSHOT will be published soon I think tonight I'm gonna make a release if everything works on your site.

**Comment by AlexKorovyansky** [comment]
Works now (with the 0.2.0 SNAPSHOT)! There is our dependecy graph 🧐
![dependency-graph](https://user-images.githubusercontent.com/479961/37069523-f07aef7a-21dd-11e8-9590-8f795fcc63eb.png)

Awesome tool, keep doing!

**Comment by canberkozcelik** [comment]
Have you got this graph with the project that has flavors in it? @AlexKorovyansky

**Comment by vanniktech** [comment]
I've just released 0.2.0 which should be available soon through mavenCentral.

**Comment by AlexKorovyansky** [comment]
> Have you got this graph with the project that has flavors in it? @AlexKorovyansky
yes

**Comment by vanniktech** [comment]
@canberkozcelik sometimes snapshot versions are cached for 24 hours so it could be that you tried a version after the PR merge but still got an old version. It's best to just use `0.2.0` now.

**Comment by canberkozcelik** [comment]
@vanniktech totally got it, I'll try new snapshot version and give my feedback according to, thx

**Comment by canberkozcelik** [comment]
@vanniktech it worked smoothly successful, really awesome tool!

**Comment by vanniktech** [comment]
Cool if any of you hit any further problems feel free to create a new issue.
