### ISSUE TITLE
Implementation not work

### ISSUE THREAD

**Issue by drdla49** [vanniktech/gradle-dependency-graph-generator-plugin#76]
I generate gradle dependency graph and in graph is missing every line with implementation dependency in submodules.
I know that this is correct by definition of implementation.
But I think this plugin should show all dependencies in all submodules. 
Any way to generate also implementation dependencies?

**Comment by vanniktech** [comment]
Try out 0.6.0-SNAPSHOT and `generateProjectDependencyGraph`
