### ISSUE TITLE
Windows 10 support?

### ISSUE THREAD

**Issue by Armaxis** [vanniktech/gradle-dependency-graph-generator-plugin#8]
Tried installing Graphviz to get a `dot` command line tool, but haven't found a working one. Is there a correct version for Win 10 that worked with this plugin?

**Comment by vanniktech** [comment]
I'm not using windows. What do you define with haven't found a working one?

**Comment by Armaxis** [comment]
Tried this https://graphviz.gitlab.io/_pages/Download/Download_windows.html and this http://wingraphviz.sourceforge.net/wingraphviz/ - both didn't add `dot` to command line for me..

**Comment by vanniktech** [comment]
Do you need to add some directory to your path? Otherwise I'd also be lost. :D

**Comment by vanniktech** [comment]
I'm going to close it. If you find a way to install graphviz's dot command line please let me know and I'll print instructions when running the tasks - just as I'm doing with 0.2.0 with Linux & Mac.

https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/master/src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt

**Comment by Armaxis** [comment]
Maybe at least keep this open, so if somebody gets the same problem they will see that it's still an open questions and that there's help needed to work on this?

**Comment by vanniktech** [comment]
Seems like in #10 someobdy already found a way of installing it. Can you confirm this works?
