### ISSUE TITLE
dependency scope specific graph

### ISSUE THREAD

**Issue by glebsts** [vanniktech/gradle-dependency-graph-generator-plugin#80]
Hello,
Thank you for a great tool.
More like a question/feature request - how could I build dependency graph only for i.e. `compile` scope? Meaning, excluding `testCompile`, or `provided` dependencies.
I'm trying to solve a problem of some libraries getting included into resulting jar for unknown reason - dependency graph svg is a good helper (svg because you can find text), but would be nice to make it partial. Hard to dig through testCompile dependencies, would like to see only compile scope.

**Comment by vanniktech** [comment]
Custom generator. https://github.com/vanniktech/gradle-dependency-graph-generator-plugin#generator-example

Specifically `includeConfiguration`. https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/master/src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt#L50

There is also a test where you can have a look at:

https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/237118c615fb7ea7f78258de91c9abf832da38df/src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTest.kt#L526
