### ISSUE TITLE
Current version not working with Gradle 4.9+

### ISSUE THREAD

**Issue by spawlak-atlassian** [vanniktech/gradle-dependency-graph-generator-plugin#82]
I have tried the latest version of the plugin (manually build SNAPSHOT) and it does not work with Gradle 4.9. 

I'm using custom generators in my project and for Gradle 4.9 I don't see tasks for my custom generators.

I think it is due to #72 because for Gradle 4.9 the task registration is not executed within `project.afterEvaluate` block hence the extension is no yet configured (the generators will be always default).

**Comment by vanniktech** [comment]
My integration test says otherwise. https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/dad722e36f60bd0fb3a2f3cc49bc49744d235a56/src/test/java/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorPluginTest.kt#L55

**Comment by spawlak-atlassian** [comment]
Your test is not applying any custom generators.

**Comment by vanniktech** [comment]
It does. https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/3c0d8ff59f69f716bbd2aac9999743fe19629155/src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorExtension.kt#L22

I'm also using custom generators in some projects with Gradle 4.9/4.10/5.1 without any problems. Hence I'm closing. If you can find a way for me to reproduce or provide a failing test case please reach out.

**Comment by hendrysetiadi89** [comment]
It is reproduceable, test project can use this:

https://github.com/MatthewPageCS/SampleModuleProject
