### ISSUE TITLE
Handle missing build.gradle file

### ISSUE THREAD

**Issue by bjorndarri** [vanniktech/gradle-dependency-graph-generator-plugin#86]
I have a submodule without a build.gradle file, since it has no configuration or dependencies other than what is specified in the root module build file.

This results in the following error:

> org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':[module]:generateDependencyGraph'.
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:54)
..
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
**Caused by: org.gradle.api.InvalidUserDataException: File '/[filesystem path]/build.gradle' specified for property 'inputFile' does not exist.**
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:64)

I solved this by creating an empty build.gradle file, but keeping an empty build.gradle file smells a bit iffy.

**Comment by vanniktech** [comment]
Having a Gradle module without a build.gradle file smells a bit iffy to me.

**Comment by bjorndarri** [comment]
Yeah, I don't really know what to say to that, except that Gradle supports submodules without a build file and no build file smells better to me than an empty build file.

Since this is becoming a war of the noses and quite subjective feel free to close this. I'll just add an empty build file when I generate dependency graphs, hell, I might event keep it under source control, since I like this plugin so much :).

**Comment by vanniktech** [comment]
What does the Gradle API say though? Is it really allowed to be null? If it is then we should honor that.

**Comment by bjorndarri** [comment]
[Subproject without build.gradle file | Gradle Forums](https://discuss.gradle.org/t/subproject-without-build-gradle-file/30673)

**Comment by vanniktech** [comment]
@bjorndarri want to create a PR that handles the case where a build.gradle file is missing?

**Comment by bjorndarri** [comment]
I'm afraid I have practically zero experience with Gradle plugin development and Kotlin, so I don't think I'm the one for the job. I may look into this at some point though, since I'm interested in both Gradle and Kotlin, but I wouldn't bet on me fixing this issue any day soon.

**Comment by vanniktech** [comment]
Do you have a sample repo how I can set up a Gradle module without a build.gradle file?

**Comment by bjorndarri** [comment]
I've created a minimal multi module example where the api module does not have a build.gradle file. The generateDependencyGraph task fails when run for the api module.
https://github.com/bjorndarri/gradle-multi-module-example

**Comment by vanniktech** [comment]
Thanks. I'll have a look when I have some spare time!
