### ISSUE TITLE
How to use custom generator with 0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by saily** [vanniktech/gradle-dependency-graph-generator-plugin#90]
Hi, I've tried latest `0.6.0-SNAPSHOT` release, but unfortunately custom generators API has somehow changed when being used with Gradle `>=4.9`. I've tried JDK10 and Gradle `4.10.3`.

Documentation should be updated how to use them, I've seen also [a fork](https://github.com/gentrio/gradle-dependency-graph-generator-plugin/commit/39bdf05a355f2bf9205215d47736a11d4c02de8e) working on this topic...

**Comment by vanniktech** [comment]
Yes. I still don't fully understand why we'd need `afterEvaluate`. I'm not keen on just adding it without understanding the underlying reason why we'd need it.

How is Gradle 5+ working for you?

**Comment by saily** [comment]
I've tried to upgrade to Gradle 5+, but still facing some issues. Any chance to get this compatible with Gradle `4.10`?

**Comment by vanniktech** [comment]
Decided to move forward and drop everything below Gradle 5.x with https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/pull/92
Everyone should really upgrade.
