### ISSUE TITLE
`NoClassDefFoundError` for `0.5.0`

### ISSUE THREAD

**Issue by handstandsam** [vanniktech/gradle-dependency-graph-generator-plugin#94]
I couldn't figure out what was wrong with `0.5.0` on a new project (I'm a first time user), but then I used `0.4.0` and saw the message saying to install `brew install graphviz`.  I think that step should be added to the `README.md` as I couldn't get it to work without it.

I did get it to work now and it's 💯 .  Thanks!  Just trying to help out the next person to use this lib.

**Comment by handstandsam** [comment]
I just tried upgrading from `0.4.0`->`0.5.0` and got 
```Caused by: java.lang.NoClassDefFoundError: org/apache/batik/i18n/Localizable```

Is there something else I need to install with `brew`?

Will use `0.4.0` for now until I know what to do to get this to work.

**Comment by handstandsam** [comment]
I now look in your release notes and see you switched to the Java version for `0.5.0`: https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/pull/40

Maybe the `brew install graphviz` is not applicable anymore for `0.5.0` but we have the other problem with class path dependencies.

**Comment by vanniktech** [comment]
`brew install graphviz	` isn't required anymore. Which JDK version are you running everything on?

**Comment by handstandsam** [comment]
That makes sense with the release notes for `0.5.0`. Thanks for confirming.

Java info for my system.
```java -version
Picked up JAVA_TOOL_OPTIONS: -Xmx8096m -XX:+HeapDumpOnOutOfMemoryError
Picked up _JAVA_OPTIONS: -Xmx8096m -XX:+HeapDumpOnOutOfMemoryError
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)```

Using android-gradle-plugin `3.4.1`
Using Gradle `5.4.1`

**Comment by vanniktech** [comment]
I believe you need JDK. JRE isn't enough.

**Comment by handstandsam** [comment]
I can build everything else with Gradle, etc though... I think this is fine.

`org/apache/batik/i18n/Localizable` isn't part of the JDK anyways, it's a part of `apache`.

**Comment by vanniktech** [comment]
I believe the graphviz java library is depending on it in some way. So I guess it's best if you open an issue there.
