### ISSUE TITLE
Task inputs are not marked, resulting in upToDate checks false positive

### ISSUE THREAD

**Issue by trevjonez** [vanniktech/gradle-dependency-graph-generator-plugin#95]
if we were to add an `@Nested` to the generator property and declare the properties within it appropriately as inputs it should result in a proper up to date check.

https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/master/src/main/kotlin/com/vanniktech/dependency/graph/generator/DependencyGraphGeneratorTask.kt#L12

looks like there was some mention to it there that remains in need of resolution as well.

**Comment by vanniktech** [comment]
Feel free to PR.
