### ISSUE TITLE
Feature request: highlight unused dependencies

### ISSUE THREAD

**Issue by KarimFikani** [vanniktech/gradle-dependency-graph-generator-plugin#99]
Is it possible to highlight unused dependencies in the generated graph?

**Comment by vanniktech** [comment]
How do you define unused dependencies?

**Comment by KarimFikani** [comment]
I was thinking if a dependency was not imported in any of the source files would be a way to identify an unused library.

Let's say we have the following:
implementation "com.a.b.c:1.2.3"
implementation "com.x.y.z:1.2.3"

dependency "com.x.y.z" is not included in any source file and gradle or Android Studio don't detect it. A quick parse through the source files we can identify that "com.x.y.z" was not used so it's unused.

Let me know what you think.

**Comment by vanniktech** [comment]
That's out of scope for this tool.

If you're on an Android project, star https://issuetracker.google.com/issues/77246430
